baseurl = "/"
languageCode = "pt-br"
title = "ilosamart"
theme = "cupper-hugo-theme"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.nav]]
    name = "blog"
    url = "/post"
    weight = 1
[[menu.nav]]
    name = "sobre"
    url = "/about"
    weight = 100
[[menu.nav]]
    name = "categorias"
    url = "/categories/"
    weight = 80
[[menu.nav]]
    name = "tags"
    url = "/tags/"
    weight = 70
[[menu.nav]]
    name = "feed"
    url = "/index.xml"
    weight = 90

[params]
    description = "Só um blog."
    footer = "oibaf setineb ilosamart | [github](https://github.com/ilosamart) | [twitter](https://twitter.com/ilosamart) | [linkedin](https://linkedin.com/in/ilosamart)"
    custom_css = ["css/theme-override.css"]

[params.social]
	twitter = "ilosamart"
	keybase = "ilosamart"
	github = "ilosamart"
    gitlab = "ilosamart"
    linkedin = "ilosamart"
